#!/bin/bash
# PreToolUse hook (matcher: Bash) — mechanically enforces architecture-implementer's
# own "Web3 no-execute rule" (see agents/architecture-implementer.md's "Rules for
# implementation") at the tool-call level, instead of resting entirely on that
# agent's prompt compliance. Blocks a Bash command that looks like a chain deploy
# or transaction broadcast (hardhat/truffle/foundry/anchor/solana/near/aptos/sui/
# multiversx/cosmwasm/starknet/stellar-soroban CLIs, a scripts/deploy/* script, or
# an npm/yarn/pnpm "deploy" script) while an implementation plan on disk currently
# reads Status: In progress
# — the window during which architecture-implementer is (or was, if interrupted)
# actively writing this project's on-chain code.
#
# Scope and limitation: this checks disk state, not "is architecture-implementer
# specifically the caller right now" — it blocks any matching Bash command, from
# any caller, while ANY plan file under docs/architecture-designer/plan/ reads
# Status: In progress. This is deliberately cautious given the domain (a wrong
# deploy can mean irreversible fund loss), but it means a stale, never-resumed
# In-progress plan from an unrelated crashed run can also block an unrelated,
# fully legitimate deploy later — resolve by finishing or superseding that plan
# (see the plugin README's "Resuming implementation plans") if this ever blocks
# something it shouldn't. Pattern coverage is necessarily a heuristic, not an
# exhaustive list of every chain toolchain's deploy command.
#
# Known bypass class: matching is plain substring detection on the literal
# tool_input.command string. It catches unobfuscated, typical invocations only —
# it does not (and cannot, at this layer) defeat deliberate obfuscation such as
# quote-splitting (fo''rge create), command substitution ($(echo forge) create),
# or piping through eval/base64. Treat this hook as a safety net for accidental
# deploys, not a security boundary against an adversarial caller.
set -uo pipefail

command -v jq >/dev/null 2>&1 || exit 0

input=$(cat)
command_str=$(printf '%s' "$input" | jq -r '.tool_input.command // empty' 2>/dev/null)
[ -z "$command_str" ] && exit 0

# Matched case-insensitively: the CLI names/subcommands below are conventionally
# lowercase, but a differently-cased invocation (e.g. "Forge Create", generated by
# a script or typed by habit) must not silently bypass this gate.
command_lc=$(printf '%s' "$command_str" | tr '[:upper:]' '[:lower:]')

contains() {
  local pattern
  pattern=$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')
  case "$command_lc" in
    *"$pattern"*) return 0 ;;
    *) return 1 ;;
  esac
}

is_safe_network() {
  case "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" in
    hardhat|localhost|local|development|ganache|test) return 0 ;;
    *) return 1 ;;
  esac
}

network_present=0
printf '%s' "$command_lc" | grep -qE -- '--network\b' && network_present=1
network_arg=$(printf '%s' "$command_lc" | grep -oE -- '--network[= ]+[A-Za-z0-9_.-]+' | head -1 | sed -E 's/--network[= ]+//')

# True only when a deploy is actually risky: no --network flag means the tool
# falls back to its own safe in-memory default, so that case is not blocked.
# A --network flag whose value could not be parsed as a plain literal (e.g. a
# shell variable or command substitution, which the regex above cannot resolve)
# is treated as unresolved and blocked rather than assumed safe.
#
# Known gap: this "no flag = safe" assumption does not hold for a Hardhat
# project whose hardhat.config.js sets a non-default `defaultNetwork` (e.g.
# `defaultNetwork: "mainnet"`) — `npx hardhat run scripts/deploy.js` with no
# --network flag then deploys to that configured network, not Hardhat's
# built-in in-memory default. Detecting this would require parsing the
# project's config file, which this hook deliberately does not attempt (same
# heuristic-not-exhaustive tradeoff as the rest of this script — see the file
# header). A project relying on a non-default defaultNetwork is not protected
# by this specific check; the scripts/deploy/* and CLI-subcommand checks above
# still apply independently.
network_is_risky() {
  [ "$network_present" -eq 0 ] && return 1
  [ -z "$network_arg" ] && return 0
  ! is_safe_network "$network_arg"
}

reason=""
if contains "scripts/deploy/"; then
  reason="invokes a script under scripts/deploy/"
elif contains "forge script" && contains "--broadcast"; then
  reason="forge script --broadcast"
elif contains "forge create"; then
  reason="forge create"
elif contains "cast send"; then
  reason="cast send"
elif contains "anchor deploy"; then
  reason="anchor deploy"
elif contains "solana program deploy"; then
  reason="solana program deploy"
elif contains "near deploy"; then
  reason="near deploy"
elif contains "aptos move publish"; then
  reason="aptos move publish"
elif contains "sui client publish"; then
  reason="sui client publish"
elif contains "mxpy contract deploy"; then
  reason="mxpy contract deploy"
elif contains "thirdweb deploy"; then
  reason="thirdweb deploy"
elif { contains "stellar" || contains "soroban"; } && contains "contract deploy"; then
  reason="stellar/soroban contract deploy"
elif { contains "stellar" || contains "soroban"; } && { contains "contract install" || contains "contract upload"; }; then
  reason="stellar/soroban contract install/upload"
elif contains "tx wasm store" || contains "tx wasm instantiate"; then
  reason="cosmwasm tx wasm store/instantiate"
elif contains "starknet deploy" || contains "sncast deploy"; then
  reason="starknet deploy"
elif printf '%s' "$command_lc" | grep -qE '(npm run|yarn|pnpm)[[:space:]]+([a-z0-9_.-]*:)?deploy(:[a-z0-9_.-]+)?([[:space:]]|$)'; then
  reason="npm/yarn/pnpm deploy script"
elif { contains "hardhat deploy" || contains "hardhat run" || contains "hardhat ignition deploy"; } && network_is_risky; then
  reason="hardhat deploy/run --network ${network_arg:-<unresolved>}"
elif contains "truffle migrate" && network_is_risky; then
  reason="truffle migrate --network ${network_arg:-<unresolved>}"
fi

[ -z "$reason" ] && exit 0

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

plan_dir="docs/architecture-designer/plan"
[ -d "$plan_dir" ] || exit 0

for f in "$plan_dir"/*.md; do
  [ -e "$f" ] || continue
  if grep -qE '^\|[[:space:]]*Status[[:space:]]*\|[[:space:]]*In progress' "$f" 2>/dev/null; then
    echo "BLOCKED: this command ($reason) looks like a chain deploy or transaction broadcast, and $f currently reads 'Status: In progress' — architecture-implementer's Web3 no-execute rule forbids executing a deploy while a plan is still being implemented. If this is an intentional deploy by the user rather than architecture-implementer, finish or supersede that plan first (see 'Resuming implementation plans' in the plugin README), or run this command outside Claude Code." >&2
    exit 2
  fi
done

exit 0
